on: [ push, pull_request ]
name: Test
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Command
        run: make
      - name: Test Go
        run: make test
  test-status:
    name: Test status
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
